services:
  - type: web
    name: telegram-crossover-bot
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python main.py"
    envVars:
      - key: BOT_TOKEN
        value: 8182668242:AAGpy6WMoYVJ5y_OLKd4FKWSFjixxggmHxY
      
